version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sit753_web_staging
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates:ro
      - ./static:/app/static:ro
    environment:
      - FLASK_ENV=development